### ISSUE TITLE
redis-audit.rb:150:in `group_key': undefined method `codepoints' for "UserRingWork":

### ISSUE THREAD

**Issue by ElvisLiu85** [snmaynard/redis-audit#47]
I use git clone redis-audit 
And install it by bundle
When I try to run it, error print out as follows:

[root@localhost script]# bundle exec ruby redis-audit.rb 127.0.0.1  6379 0 1000
Auditing 127.0.0.1:6379 dbnum:0 sampling 1000 keys
Getting a list of all 98 keys...
Auditing 98 keys...
redis-audit.rb:150:in `group_key': undefined method `codepoints' for "UserRingWork":String (NoMethodError)
	from redis-audit.rb:130:in `audit_key'
	from redis-audit.rb:111:in `audit_keys'
	from /usr/lib/ruby/site_ruby/1.8/rubygems/core_ext/kernel_require.rb:51:in `each_with_index'
	from redis-audit.rb:110:in `each'
	from redis-audit.rb:110:in `each_with_index'
	from redis-audit.rb:110:in `audit_keys'
	from redis-audit.rb:348

**Comment by postor** [comment]
i got same problem too

**Comment by patademahesh** [comment]
same problem..

```
Auditing 172.29.18.129:6379 dbnum:0 sampling 0 keys
Sampling 206747 keys...
./redis-audit.rb:158:in `block (2 levels) in group_key': undefined method `[]' for #<Enumerator: "Dheerajj-port":codepoints> (NoMethodError)
        from ./redis-audit.rb:156:in `each_codepoint'
        from ./redis-audit.rb:156:in `with_index'
        from ./redis-audit.rb:156:in `block in group_key'
        from ./redis-audit.rb:152:in `each'
        from ./redis-audit.rb:152:in `group_key'
        from ./redis-audit.rb:130:in `audit_key'
        from ./redis-audit.rb:99:in `block in audit_keys'
        from ./redis-audit.rb:97:in `times'
        from ./redis-audit.rb:97:in `audit_keys'
        from ./redis-audit.rb:358:in `<main>'
```

**Comment by eXcellme** [comment]
same problem...
>Auditing 192.168.x.x:6380 dbnum:0 sampling 0 keys
Sampling 1083 keys...
redis-audit.rb:150:in `group_key': undefined method `codepoints' for "some_key":String (NoMethodError)
	from redis-audit.rb:130:in `audit_key'
	from redis-audit.rb:99:in `audit_keys'
	from redis-audit.rb:97:in `times'
	from redis-audit.rb:97:in `audit_keys'
	from redis-audit.rb:358

**Comment by larry2208** [comment]
the same ..
Auditing 127.0.0.1:6379 dbnum:0 sampling 0 keys
Sampling 14631 keys...
bundler: failed to load command: redis-audit.rb (redis-audit.rb)
NoMethodError: undefined method `codepoints' for "id:api.o:":String
  ./redis-audit.rb:150:in `group_key'
  ./redis-audit.rb:130:in `audit_key'
  ./redis-audit.rb:99:in `audit_keys'
  ./redis-audit.rb:97:in `times'
  ./redis-audit.rb:97:in `audit_keys'
  ./redis-audit.rb:358

**Comment by zqli** [comment]
i got same problem too
