### ISSUE TITLE
invalid byte sequence in US-ASCII (ArgumentError)

### ISSUE THREAD

**Issue by 2ge** [snmaynard/redis-audit#52]
I am using binary keys - for example 'ss:' + md5_binary($string)
```
Sampling 10000 keys...
1000 keys sampled - 10% complete - 2016-11-06 20:50:53 +0100
./redis-audit.rb:146:in `match': invalid byte sequence in US-ASCII (ArgumentError)
        from ./redis-audit.rb:146:in `block in group_key'
        from ./redis-audit.rb:145:in `each'
        from ./redis-audit.rb:145:in `each_with_index'
        from ./redis-audit.rb:145:in `group_key'
        from ./redis-audit.rb:135:in `audit_key'
        from ./redis-audit.rb:104:in `block in audit_keys'
        from ./redis-audit.rb:102:in `times'
        from ./redis-audit.rb:102:in `audit_keys'
        from ./redis-audit.rb:284:in `<main>'
```

**Comment by tsgan** [comment]
Same here:
Sampling 867931 keys...
./redis-audit.rb:144:in `delete': invalid byte sequence in US-ASCII (ArgumentError)
	from ./redis-audit.rb:144:in `group_key'
	from ./redis-audit.rb:130:in `audit_key'
	from ./redis-audit.rb:99:in `block in audit_keys'
	from ./redis-audit.rb:97:in `times'
	from ./redis-audit.rb:97:in `audit_keys'
	from ./redis-audit.rb:358:in `<main>'

**Comment by vmrm** [comment]
same thing here 
```
 Auditing 127.0.0.1:6379 dbnum:0 sampling 0 keys
Sampling 2740289 keys...
./redis-audit.rb:144:in `delete': invalid byte sequence in US-ASCII (ArgumentError)
        from ./redis-audit.rb:144:in `group_key'
        from ./redis-audit.rb:130:in `audit_key'
        from ./redis-audit.rb:99:in `block in audit_keys'
        from ./redis-audit.rb:97:in `times'
        from ./redis-audit.rb:97:in `audit_keys'
        from ./redis-audit.rb:358:in `<main>
```
